# Generated by Django 5.2.7 on 2025-10-15 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Login Failed'), ('register', 'User Registration'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('role_changed', 'Role Changed'), ('membership_created', 'Membership Created'), ('membership_updated', 'Membership Updated'), ('membership_cancelled', 'Membership Cancelled'), ('membership_expired', 'Membership Expired'), ('payment_received', 'Payment Received'), ('walkin_sale', 'Walk-in Sale'), ('payment_refunded', 'Payment Refunded'), ('plan_created', 'Plan Created'), ('plan_updated', 'Plan Updated'), ('plan_deleted', 'Plan Deleted'), ('data_export', 'Data Exported'), ('report_generated', 'Report Generated'), ('settings_changed', 'Settings Changed'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('password_changed', 'Password Changed'), ('permission_denied', 'Permission Denied')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='audit_logs_user_id_e11c73_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx'),
        ),
    ]
