# Generated by Django 5.2.7 on 2025-11-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kiosk_pin',
            field=models.CharField(blank=True, help_text='6-digit PIN for kiosk check-in/out', max_length=6, null=True, unique=True, verbose_name='Kiosk PIN'),
        ),
    ]
