# Generated by Django 5.2.8 on 2025-11-17 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0005_user_kiosk_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexibleaccess",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flexibleaccess",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_walk_in_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flexibleaccess",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Archived passes are hidden but preserved for records",
            ),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_membership_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Archived plans are hidden but preserved for records",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Confirmation"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="walkinpayment",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_walkin_sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("gcash", "GCash")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference_no",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated payment reference",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usermembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="walkinpayment",
            name="method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("gcash", "GCash")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="walkinpayment",
            name="reference_no",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated payment reference",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="LoginActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Activity",
                "verbose_name_plural": "Login Activities",
                "db_table": "login_activities",
                "ordering": ["-login_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "-login_time"],
                        name="login_activ_user_id_8ea72b_idx",
                    )
                ],
            },
        ),
    ]
