# Generated by Django 5.2.7 on 2025-11-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0006_flexibleaccess_archived_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
