# Generated by Django 5.2.7 on 2025-11-19 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0007_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active_model', models.CharField(choices=[('llama3.2:1b', 'Llama 3.2 1B (Fastest, 8GB RAM)'), ('llama3.2:3b', 'Llama 3.2 3B (Balanced, 12GB RAM)'), ('phi3:3.8b', 'Phi 3 3.8B (Efficient, 12GB RAM)'), ('gemma2:2b', 'Gemma 2 2B (Fast, 8GB RAM)'), ('mistral:7b', 'Mistral 7B (High Quality, 16GB RAM)')], default='llama3.2:1b', help_text='Current active Ollama model', max_length=50)),
                ('temperature', models.FloatField(default=0.7, help_text='Creativity level (0.0-1.0). Higher = more creative')),
                ('top_p', models.FloatField(default=0.9, help_text='Nucleus sampling (0.0-1.0)')),
                ('max_tokens', models.IntegerField(default=512, help_text='Maximum response length in tokens')),
                ('context_window', models.IntegerField(default=6, help_text='Number of previous messages to keep in context')),
                ('enable_streaming', models.BooleanField(default=False, help_text='Enable streaming responses (better UX)')),
                ('enable_persistence', models.BooleanField(default=True, help_text='Save conversation history to database')),
                ('ollama_host', models.CharField(default='http://localhost:11434', help_text='Ollama server URL', max_length=200)),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot Configuration',
                'verbose_name_plural': 'Chatbot Configuration',
                'db_table': 'chatbot_config',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, help_text='Unique identifier for this conversation', max_length=100, unique=True)),
                ('title', models.CharField(blank=True, help_text='Auto-generated conversation title', max_length=200)),
                ('model_used', models.CharField(help_text='Ollama model used for this conversation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous users', max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response generation time in milliseconds', null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gym_app.conversation')),
            ],
            options={
                'verbose_name': 'Conversation Message',
                'verbose_name_plural': 'Conversation Messages',
                'db_table': 'conversation_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='conversatio_user_id_e93dff_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_id'], name='conversatio_convers_144068_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_01af31_idx'),
        ),
    ]
